Developing more robust persistence layer
DiamondLightSource/diffcalc-api pull request #5
Opened 2022-07-14 13:14 UTC by RAYemelyanova

merged saving/loading of Hkl pickles into one class, which inherits from generic class which can be used with any persistence method (in theory).

2022-07-14 14:04 UTC, garryod requested changes
Looks good, definitely a nice abstraction, comments are all minor

2022-07-14 14:04 UTC, garryod commented on src/diffcalc_API/persistence.py
> +async def createPickle(pickleFileName: str) -> Path:
This function name could be made more generic i.e. `createStore`

2022-07-14 14:04 UTC, garryod commented on src/diffcalc_API/persistence.py
> +def deletePickle(pickleFileName: str) -> Path:
This function name could be made more generic i.e. `deleteStore`

2022-07-14 14:04 UTC, garryod commented on src/diffcalc_API/persistence.py
> +class HklCalcRepo(ABC):
The term "store" may better describe a persistent structure, the term repository implies structure beyond a single item

2022-07-14 14:04 UTC, garryod commented on tests/conftest.py
> +        return
`pass` is typically used in this scenario

2022-07-14 14:04 UTC, garryod commented on src/diffcalc_API/persistence.py
> +        return diffcalcObject
I would typically move this to it's own module, allowing for one module per implementation

2022-07-14 14:04 UTC, garryod commented on src/diffcalc_API/persistence.py
> +        ...
This may be better as a `Protocol` ([PEP544](https://peps.python.org/pep-0544/))

2022-07-14 14:21 UTC, callumforrester commented on src/diffcalc_API/persistence.py
> +def deletePickle(pickleFileName: str) -> Path:
More generally, the abstraction is leaking as a result of `createPickle` and `deletePickle` still being here. I think we want to add `create` and `delete` methods to the persistence class.

2022-07-14 14:49 UTC, rosesyrett commented on src/diffcalc_API/persistence.py
> +def deletePickle(pickleFileName: str) -> Path:
I've now changed this so my 'HklCalcRepo' has create/delete methods. I think this still makes sense from a database point of view,thanks for the comments and suggestion to do it this way :)

2022-07-14 14:59 UTC, RAYemelyanova commented on src/diffcalc_API/persistence.py
> +        return diffcalcObject
OK, so would this mean for example making a folder called 'persistence' instead, and having 'HklCalcRepo.py' as a file with the definition of HklCalcRepo, and then having another file 'Pickling.py' with PicklingHklCalcRepo definition?

2022-07-14 16:16 UTC, rosesyrett commented on src/diffcalc_API/persistence.py
> +        ...
I agree - I didn't actually know this was something I could do. Makes things a lot cleaner! Thanks.

2022-07-15 08:06 UTC, garryod commented on src/diffcalc_API/persistence.py
> +        return diffcalcObject
I guess there's three structures I might adopt:

- A: Protocol in super
  ```
  diffcalc_API
  ├ hkl_calc_repo.py <- With HklCalcRepo
  └ hkl_calc_repos
    ├ __init__.py <- Empty
    └ pickling.py <- With PicklingHklCalcRepo
  ```
- B: Protocol in module `__init__`
  ```
  diffcalc_API
  └ hkl_calc_repos
    ├ __init__.py <- With HklCalcRepo
    └ pickling.py <- With PicklingHklCalcRepo
  ```
- C: Protocol in module
  ```
  └ hkl_calc_repos
    ├ __init__.py <- Empty
    ├ protocol.py <- With HklCalcRepo
    └ pickling.py <- With PicklingHklCalcRepo
  
  ```
I think my preference is for either B or C, with a slight lean towards C. Would be interesting in hearing which @callumforrester finds most pythonic

2022-07-15 08:15 UTC, callumforrester commented on src/diffcalc_API/persistence.py
> +        return diffcalcObject
C gets my vote, along with an `__all__` in `__init__.py` to make the imports nicer

2022-07-15 14:14 UTC, merged